# Generated by Django 5.2 on 2025-05-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("kitchen", "0003_alter_dish_cooks_cookgroups_cookuserpermissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cookuserpermissions",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cookuserpermissions",
            name="cook",
        ),
        migrations.RemoveField(
            model_name="cookuserpermissions",
            name="permission",
        ),
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Cook",
                "verbose_name_plural": "Cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Dish Type",
                "verbose_name_plural": "Dish Types",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
        migrations.RemoveField(
            model_name="dish",
            name="image",
        ),
        migrations.AlterField(
            model_name="cook",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="cook_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="cook",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="cook_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="kitchen.dishtype",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to="kitchen.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name="CookGroups",
        ),
        migrations.DeleteModel(
            name="CookUserPermissions",
        ),
    ]
