# Generated by Django 5.2 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_cookuserpermissions_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
